version: '3'
services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    image: travellist
    container_name: godocker
    restart: unless-stopped
    working_dir: /go/src/app
    volumes: 
      - .:/go/src/app
    ports:
      - "8080:8080"